master_credentials:
  username: master
  ssm_path: "/documentdb/${EnvironmentName}"
  password_length: 32

hostname: docdb

# cluster_parameters:
#   # These are the defaults provided by AWS
#   audit_logs: disabled
#   profiler: disabled
#   profiler_sampling_rate: 1.0
#   profiler_threshold_ms: 100
#   tls: enabled
#   ttl_monitor: enabled

# SSM Custom resource to create secret ssm parameter for master password
ssm_custom_resources:
  custom_policies:
    ssm:
      action:
        - ssm:AddTagsToResource
        - ssm:DeleteParameter
        - ssm:PutParameter
        - ssm:GetParameters
      resource: '*'
  roles:
    SSMParameterCustomResource:
      policies_inline:
        - cloudwatch-logs
        - ssm
  functions:
    SSMSecureParameterCR:
      code: handler.py
      handler: handler.lambda_handler
      runtime: python3.6
      timeout: 5
      role: SSMParameterCustomResource
